language: node_js
node_js: 
  	- "stable"
before_script: 
	- sudo apt-get install fontforge eot-utils
  	- wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
  	- unzip woff-code-latest.zip -d sfnt2woff && cd sfnt2woff && make && sudo mv sfnt2woff /usr/local/bin/
	- npm install
script: 
	- npm test